feat: Adding plugin for maxlength countdown for text based inputs
formkit/formkit pull request #1005
Opened 2023-10-19 15:01 UTC by chrisladams

2023-11-06 19:00 UTC, justin-schroeder requested changes
@chrisladams small little changes, looks great overall.

2023-11-06 19:00 UTC, justin-schroeder commented on packages/addons/src/plugins/maxlengthCountdown.ts
> +        }
The same memoization technique discussed in the review of #1000 could apply here too. Let’s do as little work inside this input event as possible.

2023-11-06 19:00 UTC, justin-schroeder commented on packages/addons/src/plugins/maxlengthCountdown.ts
> +}
```suggestion
}

```

2023-11-06 19:00 UTC, justin-schroeder commented on packages/addons/src/plugins/maxlengthCountdown.ts
> +    node.addProps(['maxlengthStringCount'])
```suggestion
    node.addProps(['maxlengthCountdown', 'maxlengthRemainingText', 'maxlengthStringCount'])
```

2023-11-09 13:44 UTC, chrisladams commented on packages/addons/src/plugins/maxlengthCountdown.ts
> +    node.addProps(['maxlengthStringCount'])
Updated

2023-11-09 13:45 UTC, chrisladams commented
@justin-schroeder updated! Thanks for the review

2023-11-09 14:48 UTC, merged