Feature/tailwind genesis theme
formkit/formkit pull request #548
Opened 2023-01-18 21:21 UTC by andrew-boyd

This adds an exportable version of the Tailwind genesis theme. This will be used in the playground once beta.13 launches to remove the inline theme and replace it with an imported variable.

2023-01-18 21:25 UTC, andrew-boyd commented
They playground updates will occur in the `@formkit/vue2-live-code-editor` package independently but are themselves dependent upon the theme being an exportable item in `beta.13`

2023-01-18 21:26 UTC, GustavoFenilli reviewed
Looks good to me, people still can change what they want from it by changing the property.

2023-01-19 18:51 UTC, justin-schroeder requested changes

2023-01-19 18:51 UTC, justin-schroeder commented on packages/themes/src/tailwindcss/index.ts
> +}
```suggestion
}

```

2023-01-19 18:51 UTC, justin-schroeder commented on packages/themes/src/tailwindcss/genesis.ts
> +}
```suggestion
}

```

2023-01-19 19:35 UTC, merged