Feature/zod
formkit/formkit pull request #691
Opened 2023-05-05 16:12 UTC by andrew-boyd

Adds support for validating a FormKit form with Zod schema and setting form errors from a ZodError object with the new `node.setZodErrors` extension.

2023-05-05 19:04 UTC, justin-schroeder requested changes
Awesome work @andrew-boyd! I've added a few items to tick off, but overall it looks great.

2023-05-05 19:04 UTC, justin-schroeder commented on packages/zod/package.json
> +    "@formkit/core": "0.16.5"
If you keep `whenAvailable` — which I’m not 100% sure we need — we’ll need to add `@formkit/utils` as a dependency — even though it is a dependency of `@formkit/core` some module resolution algos wont install it without shamefully hoisting (like pnpm).

2023-05-08 15:27 UTC, andrew-boyd commented
Ok @justin-schroeder, changes made. Open to suggestions on getting around `whenAvailable` but for now have added utils as a dependency.

2023-05-09 15:09 UTC, andrew-boyd reviewed
These changes have been addressed

2023-05-09 17:52 UTC, justin-schroeder commented
I forgot to mention, we currently have to add module augmentations to our build script because api-extractor is unable to recognize them and they always get stripped. I’ve done this now 👍

2023-05-09 17:53 UTC, merged